# Generated by Django 2.0.3 on 2018-03-09 03:25

from django.db import migrations, models
import django.db.models.deletion


def create_continent(apps, schema_Editor):
    Continent = apps.get_model('continents', 'Continent')

    Continent.objects.create(name='america', translation='america', color='#D22')
    Continent.objects.create(name='europa', translation='europe', color='#AE4')
    Continent.objects.create(name='asia', translation='asia', color='#F33')
    Continent.objects.create(name='africa', translation='africa', color='#34D')
    Continent.objects.create(name='antartica', translation='antarctica', color='#385')
    Continent.objects.create(name='australia', translation='australia', color='#DEA')


class Migration(migrations.Migration):
    dependencies = [
        ('continents', '0001_initial'),
        ('countries', '0002_auto_20180309_0311'),
    ]

    operations = [
        migrations.RunPython(create_continent),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continents.Continent'),
            preserve_default=False,
        ),
    ]
