# Generated by Django 2.0.3 on 2018-03-11 01:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='is_active',
            new_name='active',
        ),
    ]
